### ISSUE TITLE
The tutorial "Build Bot Framework bots with Microsoft Graph" will fail in Bot Emulator as written

### ISSUE THREAD

**Issue by BobGerman** [microsoftgraph/msgraph-training-botframework#2]
The Bot Emulator requires ngrok and an ngrok setup step in order to work with OAuth login prompts. This is missing from the tutorial and needs to be added.

**To Reproduce**

1. Follow the steps as written in the tutorial here: https://docs.microsoft.com/en-us/graph/tutorials/bot-framework
2. At the end of the step, "Add Microsoft identity platform authentication", the Bot emulator will fail to launch the oauth popup with a slightly cryptic message about ngrok

**Expected behavior**
At the end of the step, "Add Microsoft identity platform authentication", the Bot emulator should display an Azure AD login popup (browser) and allow the user to log in and view their access token.

Suggesting the following changes:

* The missing instructions are here in another tutorial: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#configure-the-emulator-for-authentication
Specifically the section "Configure the emulator" should be copied into this tutorial.
* ngrok should be added to the prerequisites in the 1st page
* The note at the bottom of the "Add Microsoft identity platform authentication" page is misleading; restarting the Bot emulator does not help; setting up the bot emulator correctly is what fixed it for me.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: n/a - Bot Emulator
- Version:  v4,11,9

**Comment by jasonjoh** [comment]
Thanks Bob! My emulator was already configured for ngrok, so I missed having to configure it as a step. I'm curious about this:

> The note at the bottom of the "Add Microsoft identity platform authentication" page is misleading; restarting the Bot emulator does not help; setting up the bot emulator correctly is what fixed it for me.

I had the problem pretty consistently even though I already had ngrok setup. However I didn't tick the version 1.0 token option. I'm guessing that's the difference. I'll test it out and update.

**Comment by BobGerman** [comment]
Awesome - thanks for the quick response!

**Comment by jasonjoh** [comment]
Turns out it was the **Run ngrok when the Emulator starts up** option that needed to be enabled.

**Comment by jasonjoh** [comment]
This was fixed in #5
