### ISSUE TITLE
Stuck at running end of "At the end of the step, "Add Microsoft identity platform authentication" (Ngrok properly configured)

### ISSUE THREAD

**Issue by gitguy007** [microsoftgraph/msgraph-training-botframework#4]
Hi, I am having a wee bit of a problem running the bot at the end of the step, "Add Microsoft identity platform authentication".

I have tried using the codes I am following in the tutorial as well as the sample code provided in this repository but it does not show welcome message or any action when I type in anything in the chat window.

Appreciate any advice.

I have configured emulator ngrok as per below :

![image](https://user-images.githubusercontent.com/23579183/120251076-f1b3ed00-c2b2-11eb-99f6-34a781a6c6f1.png)

However, when I run the emulator, i am not getting the Welcome message. When I tried to debug, it can run only the methods in Startup.cs but not MainDialog.cs or OnMembersAddedAsync in CalendarBot.cs.

![image](https://user-images.githubusercontent.com/23579183/120251137-2031c800-c2b3-11eb-94e5-7753dd4f6150.png)

Desktop (please complete the following information):

OS: Windows 10
Browser: n/a - Bot Emulator
Version: v4.13.0

**Comment by jasonjoh** [comment]
Sorry you're having issues! A few things to check/try:

- Enable the "Use a sign-in verification code for OAuthCards" option
- Ensure that your project is running and that if you go to http://localhost:3978 you see a page saying your bot is ready
- Check to see if any requests are going through ngrok by going to http://localhost:4040
- Make sure that you've supplied the correct application ID and password in your Bot configuration (https://github.com/microsoftgraph/msgraph-training-botframework/blob/main/tutorial/04-add-aad-auth.md#test-authentication)

**Comment by gitguy007** [comment]
Thanks for the steps above.

Sign-in verification is enabled. I have triple checked all the Application ID and Password.

FYI, in the CalendarBot configuration file, the instructions was stated to use 'https', I have instead changed it to 'http'.

I am not encountering 404 error as per screenshot. In ngrok, it is returning this error.

{
    "code": "ResourceNotFound",
    "message": "/ does not exist"
}

Again, to reiterate, the bot doesn't seem to call up MainDialog.cs although it can run the AddTransient method in Startup.cs. 

I am not sure what to do next.

![image](https://user-images.githubusercontent.com/23579183/120555517-c570ab80-c42d-11eb-9a5f-769afd9fdb1f.png)

**Comment by jasonjoh** [comment]
Thanks for letting me know about the `https` in the instructions, I'll get that fixed. It should be `http`.

![image](https://user-images.githubusercontent.com/8966342/120824621-a0ac2f00-c526-11eb-9b88-e054524c8e9c.png)

The 404's on `GET /` are fine. I see that too, even when I'm not doing anything with the bot. I suspect there may be some process in the wild just trying random ngrok URLs. Looking at the headers on the request, the user agent indicates it's coming from the node-fetch library.

![image](https://user-images.githubusercontent.com/8966342/120826253-3ac0a700-c528-11eb-98cf-0ecbef7eda3e.png)

Anyway, to the problem at hand:

- You won't hit MainDialog.cs until a request actually comes in. So my thinking here is that the emulator is not communicating successfully with your instance. The code in Startup.cs does run when you start the app, it isn't waiting for an incoming request.
- The reason I'm asking about your ID & password is there are two sets of app ID and password. There's the one for the Bots Channel registration (`Graph Calendar Bot` in the tutorial), and there's the one for auth (`Graph Calendar Bot Auth` in the tutorial). I just want to confirm that the values you put into the emulator config are the ones for `Graph Calendar Bot` and not  for `Graph Calendar Bot Auth`. The behavior I see if I put the wrong values into the emulator match what you are currently seeing. No traffic shows up in ngrok and requests return a 400. If you do make changes to these values, you need to close all open tabs in the emulator and reopen the bot. Immediately on opening a chat with the bot in the emulator, you should see MainDialog's constructor being called.
